server:
  port: ${PORT:${SERVER_PORT:8080}}


spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        Locator:
          enabled: true
      routes:
        - id: products
          uri: lb://productos
          predicate:
            - Path=/api/v1/productos/**
        - id: reviews
          uri: lb://review
            -Path=/review/**
  


info:
  application:
     name: gateway
    
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    gateway:
      enablesd: true
        
  endpoint:
    web:
      expose:
        include: gateway
